### ISSUE TITLE
Need more nerd tree color scheme

### ISSUE THREAD

**Issue by atsusta** [ajmwagar/vim-deus#10]
Hi. I felt good and refreshed about deus.
But the more **Nerd tree** support, the more elegant color scheme it would be.
How about add **directories' color** for differ from regular files?

![nerd](https://user-images.githubusercontent.com/7046491/32472185-accd92a6-c3a4-11e7-94c7-aba3c7fd6088.png)

**Comment by ajmwagar** [comment]
If you update to the latest version it should work. I have been using NERd Tree with no problem. 

What version of vim are you using?
What version of nerd tree?
What os?

> Here is an example of NERD Tree Support.

![duesnerdtree](https://user-images.githubusercontent.com/25015651/32903886-0179f0a8-caab-11e7-91ca-a55a3b6a51c4.png)

**Comment by ajmwagar** [comment]
Also can I see your vimrc

**Comment by ajmwagar** [comment]
See if adding:

 ```                                                                                                                                                                                   
   let NERDTreeMinimalUI = 1                                                                                                                                                                                                                                         
   let NERDTreeDirArrows = 1                                                                                                                                                                                                                                         
   let NERDTreeQuitOnOpen = 1                                                                                                                                                                                                                                        
   let g:NERDTreeChDirMode = 2 
```
Helps

**Comment by atsusta** [comment]
Sorry for checking comments late;(
Adding above options helped.
Thanks for your help.
