### ISSUE TITLE
Several enhancements for color usage

### ISSUE THREAD

**Issue by alexanderjeurissen** [ajmwagar/vim-deus#11]
Hi, First of all I love the vim-deus colorscheme it seems like the lovechild of Gruvbox + OneDark ;-)

Whilst using it I noticed some elements of the UI that I thought didn't really match the overall look. so I added some manual `hi!` to my vimrc so I'd thought I share them in case you're interested in merging these changes upstream.

changed highlighting rules:
```
    hi! link SignColumn LineNr
    hi! VertSplit guibg=#242a32
    hi! StatusLine guifg=#242a32 guibg=#ebdab2
    hi! StatusLineNC guifg=#242a32 guibg=#ebdab2
    hi! CursorLineNr guibg=#242a32 guifg=#ebdab2

    hi! SignColumn guibg=#242a32
    hi! SignifySignAdd guibg=#242a32 guifg=#99c379
    hi! SignifySignDelete guibg=#242a32 guifg=#fb4733
    hi! SignifySignChange guibg=#242a32 guifg=#8ec07b

    hi! AleWarningSign guibg=#242a32 guifg=#ebdab2

    hi! CursorLine guibg=#292f37
    hi! ColorColumn guibg=#292f37
```

before (original vim-deus):
![screen shot 2017-11-26 at 11 43 59](https://user-images.githubusercontent.com/1220084/33239293-201e9f62-d29f-11e7-812c-a28328910721.png)

after ( with my highlight rules):
![screen shot 2017-11-26 at 11 38 47](https://user-images.githubusercontent.com/1220084/33239287-f57faf8a-d29e-11e7-8772-a4acfb003505.png)

let me know what you think

**Comment by antenore** [comment]
Personally I love it!

**Comment by ajmwagar** [comment]
I like it as well! I’ll merge it in soon.

**Comment by ajmwagar** [comment]
@alexanderjeurissen could you open a pull request? I will merge it in as soon as possible.

**Comment by ajmwagar** [comment]
Done! Please pull to the latest version!
