### ISSUE TITLE
ListMarker color in Markdown.

### ISSUE THREAD

**Issue by Gomme-** [ajmwagar/vim-deus#17]
Hello, 

This is not really an issue. I find the ListMarker color in Markdown (deusGray) not visible enough. I am now using deusPurple which I find quite nice. Of course this is subject to personal taste. but if you ( @ajmwagar )  agree on this, that could be an good change to make I think.

**Comment by ajmwagar** [comment]
Sorry for the delay. I have been away from GitHub for awhile. I'd be happy to make the change.
