### ISSUE TITLE
Spellcheck, Cursorline, and Cursorcolumn highlighting doesn't work in Tmux

### ISSUE THREAD

**Issue by parmort** [ajmwagar/vim-deus#18]
In Tmux, I ran into a few problems.

Cursor line and column don't show up in Tmux, but do outside of Tmux. Spellcheck doesn't work at all for me, both in and out of Tmux. Otherwise I think it is an awesome colorscheme

**Comment by ajmwagar** [comment]
Glad you think so. I am assuming you are having these issues with the advice provided in the README.md. If you don't I recommend adding them.

Otherwise, I will look into a fix.

**Comment by ajmwagar** [comment]
Tmux is missing TrueColor support. https://github.com/tmux/tmux/issues/34

There is a patch.

What tmux version are you using?

**Comment by parmort** [comment]
Thank you @ajmwagar. Eventually, after figuring out how to turn Tc on in Tmux, it all works.

**Comment by ajmwagar** [comment]
Great!
