### ISSUE TITLE
Inserts 'ff' everywhere using specific 'guicursor' settings

### ISSUE THREAD

**Issue by lithammer** [ajmwagar/vim-deus#2]
Using this `vimrc` in Neovim 0.2.0 and iTerm 3.1 beta 5 causes the characters `ff` to appear everywhere. Just entering insert mode in an empty buffer makes them appear for example. Removing the `guicursor` setting fixes the issue. So something with blinking cursors is causing problems.

```vim
call plug#begin()
Plug 'ajmwagar/vim-dues'
call plug#end()
set background=dark
set termguicolors
colorscheme dues

set guicursor=n-v-c:block,i-ci-ve:ver25,r-cr:hor20,o:hor50
 \,a:blinkwait700-blinkoff400-blinkon250-Cursor/lCursor
 \,sm:block-blinkwait175-blinkoff150-blinkon175
```

I'm reporting here since this doesn't happen with other color schemes. The `guicursor` value is taken straight out of `:h guicursor`

<img width="398" alt="screen shot 2017-06-21 at 17 39 19" src="https://user-images.githubusercontent.com/177685/27393104-a0049a06-56a8-11e7-9080-6f33f81e431d.png">

**Comment by ajmwagar** [comment]
# Thanks for letting me know! #

I will look into this on my end. Could you try commenting out the stuff having to do with the cursor blinking in your .vimrc and see if it works?

Will look into this tomorrow.

**Comment by lithammer** [comment]
I mean, if I use the default value for `guicursor`, which is `n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20`, it works fine. And by removing `a:blinkwait700-blinkoff400-blinkon250-Cursor/lCursor`, it also works.

**Comment by ajmwagar** [comment]
I tried this in GVIM with your settings and it worked fine. I will continue testing on normal vim. 

Could you provide a more detailed description of your setup to help me recreate this bug?

**Comment by ajmwagar** [comment]
This does not seem to affect me. I am using GVim and the vim on windows bash. I am sorry I don't know why you're having errors.

**Comment by lithammer** [comment]
It seems like the issue only happens specifically with Neovim and iTerm on macOS. Tested in MacVim without issues. And using Terminal.app worked too (except for broken colors, but that's another issue).

I think we can close this for now unless more people start having this issue. Might not even be related to your colorscheme, it just happens to be that your colorscheme triggers a bug in iTerm or something.

**Comment by Ding-Fan** [comment]
I meet the same problem with colorscheme gruvbox. Neovim and iTerm on macOS. And I delete my setting for cursor shape `set guicursor=n-v-c:block-Cursor/lCursor-blinkon0,i-ci:ver25-Cursor/lCursor,r-cr:hor20-Cursor/lCursor` then the quirk `ff` disappear.

**Comment by lithammer** [comment]
I did some bisecting and narrowed it down to this line, if I comment it out the issue disappears. Not sure what to make of it though, maybe inverse doesn't work all too well with a blinking cursor. Or maybe it's a bug in Neovim?

https://github.com/ajmwagar/vim-deus/blob/edb634b62ebb3ad20a99db2dd137047d0bdb6dbc/colors/deus.vim#L464

**Comment by lithammer** [comment]
Also, if I disable (or rather don't enable) `termguicolors` it works fine too.
