### ISSUE TITLE
Add base16 support for deus

### ISSUE THREAD

**Issue by Nicktho** [ajmwagar/vim-deus#20]
Hey, I was wondering if this theme is base 16 compatible. If so, could you match the colors to the base16 numbers? I had a go myself but I don't they are declared in order.

**Comment by ajmwagar** [comment]
Will look into it.

**Comment by ajmwagar** [comment]
Right now it is not. I will build a base16 source for Deus. 

I'll keep updating this thread.

**Comment by distefam** [comment]
Any update on this?
