### ISSUE TITLE
Changing a color

### ISSUE THREAD

**Issue by MatthewCushing** [ajmwagar/vim-deus#21]
First off, thank you for this incredible color scheme.  It blows me away, I've been using it for quite some time now and don't think I will ever change.

But onto what I came here for.  I assumed I could just change or add a color by editing the deus.vim file in the colors folder.  I have never tried editing a plugin before but assumed it was as simple as this so correct me if I'm wrong please.  Anyways, the reason for this was that I added a plugin called vim-cpp-enhanced-highlight which adds functionality to highlight certain keywords in c++ that didn't before.  It works great, except when it comes to functions.  The bold green color used as much as it is just doesn't appeal to me.
![functioncolor](https://user-images.githubusercontent.com/10594068/46788779-289af600-ccf8-11e8-94bd-886d95d6c30d.png)
So I decided to change it.  I found function name set to deusGreenBold under syntax highlighting after I didn't find anything under the C++ specific area.  I then went to where deusGreenBold was defined and decided I really liked this dark bluish color here:
![bluecolor](https://user-images.githubusercontent.com/10594068/46789092-efaf5100-ccf8-11e8-8d6c-009256ecf6fd.png)
Testing the hex values you have set for the colors I assumed it was either Fg0 or Fg2.  So I decided to define a bold Fg0 and test it.  Under "deus Hi Groups" I added the following:
`call s:HL('deusFg0Bold', s:fg0, s:none, s:bold)`
I then changed the Function Name color to:
`hi! link Function deusFg0Bold`
I saved the file and reloaded my cpp files and they stayed the same color.  I tried changing it to deusYellowBold and nothing changed.  I tried updating plugins through vundle with :PluginUpdate and nothing changed.  I've tried resourcing my vimrc, dues.vim, my cpp files.  I have no idea what to do :(

I would really appreciate any help you have to offer.

Thanks!

**Comment by ajmwagar** [comment]
MrCush,

I am glad to hear you are enjoying the color scheme. 

Thank you for your feedback. I will look into the highlighting issues and try to create a fix. I have done this sort of thing before.

I will try to ship this today.

Please let me know if you run into any more issues.

Best,

Avery

**Comment by ajmwagar** [comment]
MrCush, 

please try adding the following to you `.vimrc` after you set the colorscheme.

```
hi! link Function deusBlue
```
or 
```
hi! link Function deusAqua
```

Which ever you perfer.

This should change the color.

**Comment by MatthewCushing** [comment]
@ajmawagar Thanks! I’ll give it a shot when I get home from work
