### ISSUE TITLE
syntax highlight color ?

### ISSUE THREAD

**Issue by mckellyln** [ajmwagar/vim-deus#22]
Hi,
Thank you for vim-deus, it is awesome.  I do have one question - not sure where is best to ask so I thought I'd post it here.
Occasionally on a vim vundle PluginUpdate I see some comments from commits that have a black
color, probably either 0 or 16 or 232 on the 256 scale.  I have attached a png to illustrate.
My question is - do you have any idea where this color is defined ? so could I change it to be a little more readable.
See the line near the bottom that starts with "Merge pull request #360 ..."

Thank you for your software,
-m

![vim-deus-dark-screenshot](https://user-images.githubusercontent.com/5116200/57663782-67ad6480-75c3-11e9-9678-ed2781b324f1.png)

**Comment by ajmwagar** [comment]
Hey, I've noticed this too. I will look into fixing it.

**Comment by ajmwagar** [comment]
I figured it out.

It was the `NonText` and `SpecialKey` highlight groups that were getting set to one of the background colors.

What color do you think it should be changed to? I'm thinking orange but that's just me.

**Comment by ajmwagar** [comment]
I'll change it to orange for now for readability. But if you think it should be something else I'll change it accordingly.

**Comment by mckellyln** [comment]
@ajmwagar thank you so much.

**Comment by ajmwagar** [comment]
No problem @mckellyln

**Comment by mckellyln** [comment]
@ajmwagar Hi.  Just fyi, I also noticed an issue with the Ignore group color and added:
```
hi! link Ignore deusPurple
```
to my env for this.
It was showing up too dark for me in fugitive Gblame when there are changes not yet committed.

**Comment by mckellyln** [comment]
Fixed in commit ce0d585c15e26f0c42c5a992bd421830712da255
Thanks again.
