### ISSUE TITLE
Add toggle for changing contrast of SignColumn background

### ISSUE THREAD

**Issue by gujiaxi** [ajmwagar/vim-deus#24]
Below is a deus solorschemed screenshot with [ALE](https://github.com/w0rp/ale/) enabled. The background color of the sign column seems too abrupt. Maybe it is better to set the background color of the sign column the same with the general background.

![](https://i.imgur.com/sNe8s5y.png)

**Comment by ajmwagar** [comment]
hmm... It looks like Deus is misconfigured on your system.

This is what it looks like on my machine:
![deus](https://user-images.githubusercontent.com/25015651/60070701-672ce100-96cc-11e9-8767-7274710d131f.jpg)

Are you using Tmux or a Terminal emulator without true-color support?

If you are, I'd suggest moving to something that does support true-colors. The [README.md](https://github.com/ajmwagar/vim-deus#troubleshooting) explains how to set up both (neo)vim and your terminal for true-colors.

If you still have problems, let me know and I will try and help troubleshoot.

**Comment by gujiaxi** [comment]
@ajmwagar After enabling true color for my terminal and vim, the color looks much better. My suggestion of making the sign column transparent (or say, be the same with the general background color) is to make this colorscheme look both good with/out true color support. The screenshot in #25 looks not bad even with true color disabled. It is of course just a suggestion. Nice work!

**Comment by ajmwagar** [comment]
Thanks! I'm glad you figured it out. Personally, I prefer the contrast with the cursor column. However, I'd like this project to have user input and have you all be able to make decisions as well.

Regarding this issue, why not have both? May I suggest adding a toggle for it? Maybe you could add that into #25.

What do you think?

**Comment by gujiaxi** [comment]
After reviewing the related source code, I find that the toggle function is implemented already.

> let g:deus_sign_column = 'bg0'

So... we can just feel free to close this PR and the corresponding Issue?
