### ISSUE TITLE
What do you need to add to neovim config when using vim-plug?

### ISSUE THREAD

**Issue by AdamBD** [ajmwagar/vim-deus#31]
Hi,

I install using vim-plug but the color scheme doesnt take effect. 

Tried:
`colorscheme dues`
`colors deus`

Neither do anything.

Thoughts?

**Comment by ajmwagar** [comment]
it would be `colorscheme deus` not "dues."

Make sure you're spelling it right, and not overriding it with another color scheme later down in your .vimrc.

**Comment by AdamBD** [comment]
Wow major fail, sorry for hassling you with this : /
