### ISSUE TITLE
Airline theme missing

### ISSUE THREAD

**Issue by noomly** [ajmwagar/vim-deus#4]
I have vim-airline and vim-airline-themes installed with vim-plug; everything uptodate.

When I do ":Airlinetheme dues" I get "The specified theme cannot be found".

Is there something I missed?

**Comment by ajmwagar** [comment]
Hi there,

I'm currently working on an automated fix. I found if you copy the airline theme, and rename it to duesAirline and put it in your `.vim/bundle/airlinethemes/autoload/airline/themes/` directory it should work when you call `:AirlineTheme duesAirline`

I am working to see if the developer would let me put it automatically in the Airlinetheme repo.

**Comment by noomly** [comment]
Thanks for the answer!

You should try to do a pull request, I can't find any reason for them to refuse it ;)

Btw good job for your colorscheme, I really appreciate it.

**Comment by ajmwagar** [comment]
Thank you noomly it means a lot!

**Comment by ajmwagar** [comment]
I added a pull [request](https://github.com/vim-airline/vim-airline-themes/pull/92) to the airline-themes repo. Closing.
