### ISSUE TITLE
Theme appears to be identical to gruvbox

### ISSUE THREAD

**Issue by plasmik010** [ajmwagar/vim-deus#6]
To reproduce:

Vundle lines:
Plugin 'ajmwagar/vim-dues'
Plugin 'morhetz/gruvbox'

Apply theme:
:colorscheme gruvbox
:colorscheme dues

**Comment by ajmwagar** [comment]
Hmm that's very odd! 

what is you setup?

It could be a bug. Do other colorschemes work?

**Comment by ajmwagar** [comment]
It's seems to be a bug in the 16 bit colors, could you enable termguicolors and see if it fixes it?

**Comment by plasmik010** [comment]
Setting termguicolors helped in xterm, but screwed urxvt.

**Comment by ajmwagar** [comment]
I'm reopening this when because I realized it is important to adapt to all terminal setups.

**Comment by ajmwagar** [comment]
I added a fix for this (see the readme).

**Comment by nguymin4** [comment]
Hi @ajmwagar, I still have the issue with urxvt, gvim works just fine
 
![screenshot from 2017-10-02 20-19-12](https://user-images.githubusercontent.com/6953273/31090131-3c5efac0-a7af-11e7-8363-ac0004a692b4.png)
