### ISSUE TITLE
Setting cursorcolumn with highlighted search patterm make characters invisible

### ISSUE THREAD

**Issue by antenore** [ajmwagar/vim-deus#7]
In my vimrc I've set corsurcolumn and cursorline.

If I search for a pattern, all the characters highlighted in the same column are black on black, so they become invisible. 

I'm not sure how to fix this because I don't know if there are any drawbacks changing cursorcolumn colors.

![selection_011](https://user-images.githubusercontent.com/5975/27608252-0be4ae22-5b87-11e7-9614-49013b60e6a3.png)

**Comment by antenore** [comment]
I forgot to mention that currently the CursorColumn is set to:
```
CursorColumn term=reverse ctermbg=242 guibg=Grey40
```
I don't know from where it comes from as it's not set by vim-dues, neither from any of my vim files

**Comment by ajmwagar** [comment]
Hmm...  What plugin are you setting that too... I don't have it, nor any knowledge on which plugin it's from.

**Comment by antenore** [comment]
It's a standard feature, anything special.

**Comment by ajmwagar** [comment]
Could you share more of your .vimrc (or the whole thing) so I can debug?

**Comment by antenore** [comment]
Yes, sure:

https://github.com/antenore/dotfiles/blob/master/vim/.vimrc

The relevant line is:

https://github.com/antenore/dotfiles/blob/master/vim/.vimrc#L152

**Comment by antenore** [comment]
Now it works perfectly, I've applied the settings you have advised in the README and everything is fine!!!

Thanks!
