### ISSUE TITLE
error in win10 with bash on ubuntu on windows

### ISSUE THREAD

**Issue by candywater** [ajmwagar/vim-deus#8]
thanks a lot for the amazing color set.
when I use the newest version (which committed  on Jun 28, 2017)
it says 

> line 1210:
> E128: Function name must start with a capital or "s:": deusHlsShowCursor()
> line 1212:
> E193: :endfunction not inside a function
> line 1214:
> E128: Function name must start with a capital or "s:": deusHlsHideCursor()
> line 1216:
> E193: :endfunction not inside a function

this is the error line
```
function! deusHLsShowCursor()
```
and then i fixed them like this 
```
function! s:deusHLsShowCursor()
```

I am a new vimer and I don't know if I fixed them correctly.

**Comment by antenore** [comment]
This is a more generic error, also on Linux it's the same.

```
Error detected while processing /home/tmow/.dotfiles/vim/.vim/bundle/vim-dues/colors/deus.vim:
line 1210:
E128: Function name must start with a capital or "s:": deusHlsShowCursor()
line 1212:
E193: :endfunction not inside a function
line 1214:
E128: Function name must start with a capital or "s:": deusHlsHideCursor()
line 1216:
E193: :endfunction not inside a function
line 1210:
E128: Function name must start with a capital or "s:": deusHlsShowCursor()
line 1212:
E193: :endfunction not inside a function
line 1214:
E128: Function name must start with a capital or "s:": deusHlsHideCursor()
line 1216:
E193: :endfunction not inside a function
```
